### PR TITLE
Reserved words for vfolder

### PR DESCRIPTION
**Pull request by kyujin-cho**
This PR adds reserved words feature for vFolder.

### CODE REVIEW

**Comment by achimnol** [comment]
Also, please add `.ssh` to the list of reserved words as well.

**Comment by achimnol** [comment]
And for dotfiles that we automatically mount for all session by default (e.g., `.bashrc`), if the user provides them as user-specific dotfiles, the user-defined ones must precede.

**Comment by kyujin-cho** [comment]
Ticket: OP#188

**Comment by achimnol** [comment]
Also, please add some unit tests for those functions, as a practice.

**Pull request merged**
