### PR TITLE
Add an option to auto-cancel a pending session after specified timeout

### PR DESCRIPTION
**Pull request by vesselofgod**
resolves: https://github.com/lablup/backend.ai/issues/337
Related to: https://github.com/lablup/backend.ai/issues/343

**Add an option to auto cancel a pending session after specified timeout**
- **Get pending_timeout option value to the 'scheduler_opt' and if it's not zero, compare pending_timeout with duration in Pending**
- **Get created_at value to the 'PendingSession' and calculate status duration in Pending**

pending_timeout PR

- **Add a pending_timeout option in scheduler_opt using trafaret**
structured

### CODE REVIEW

**Comment by achimnol** [comment]
Please merge the main branch to resolve a conflict with addition of `StructuredJSONBColumn` in both #523 and here.

**Review by achimnol — CHANGES_REQUESTED** [review]
Could you write a test case by setting `created_at` to a time in the past?

**Comment by vesselofgod** [comment]
> you write a test case by setting `created_at` to a time in

ok! I got it!

**Comment by achimnol** [comment]
> > you write a test case by setting `created_at` to a time in
> 
> ok! I got it!

What I meant is to create a new test case with a specific created_at time set in the past (maybe subtract from the current timestamp) and test actual status transition, not just changing the values of timestamps in the test fixtures...

**Comment by vesselofgod** [comment]
> > > you write a test case by setting `created_at` to a time in
> > 
> > 
> > ok! I got it!
> 
> What I meant is to create a new test case with a specific created_at time set in the past (maybe by subtracting from the current timestamp) and test actual status transition, not just changing the values of timestamps in the test fixtures...

I'll add a new test case within this week :)

**Comment by vesselofgod** [comment]
I tried to add a test cases and commit, but error occurred.
I think it's a branch related problem, so I'll solve it and commit.
b

**Comment by achimnol** [comment]
Now need to perform an integratino test.

**Pull request merged**
